In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

1.6.0


In [5]:
hello = tf.constant("hello")

In [6]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [7]:
with tf.Session as sess:
    sess.run(hello)

AttributeError: __enter__

In [8]:
world = tf.constant("world")

In [9]:
with tf.Session as sess:
    sess.run(hello+world)

AttributeError: __enter__

In [10]:
with tf.Session as sess:
    result = sess.run(hello+world)

AttributeError: __enter__

In [11]:
with tf.Session() as sess:
    sess.run(hello+world)

In [14]:
with tf.Session() as sess:
    result = sess.run(hello+ ' ' + world)

In [15]:
result

b'hello world'

In [16]:
const = tf.constant(10)

In [17]:
const

<tf.Tensor 'Const_2:0' shape=() dtype=int32>

In [18]:
fill_mat = tf.fill((4,4), 10)

In [19]:
fill_mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [23]:
my_zeros = tf.zeros((4,4))

In [25]:
my_zeros = tf.ones((4,4))

In [26]:
myrand = tf.random_normal((4,4), mean=0, stddev=1.0)

In [27]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [28]:
my_zeros = tf.zeros((4,4))

In [29]:
my_ones = tf.ones((4,4))

In [30]:
my_ops = [const, fill_mat, my_zeros, my_ones, myrand, myrandu]

In [31]:
print(my_ops)

[<tf.Tensor 'Const_2:0' shape=() dtype=int32>, <tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>, <tf.Tensor 'zeros_1:0' shape=(4, 4) dtype=float32>, <tf.Tensor 'ones_1:0' shape=(4, 4) dtype=float32>, <tf.Tensor 'random_normal:0' shape=(4, 4) dtype=float32>, <tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>]


In [32]:
sess = tf.InteractiveSession()

In [33]:
for opt in my_ops:
    sess.run(opt)

In [34]:
for opt in my_ops:
    print(sess.run(opt))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-1.3336977  -1.2571433   0.92396194 -1.5858063 ]
 [-1.5218801   0.22353542  1.3303581  -1.4708345 ]
 [-0.08460081 -1.7543142  -0.22869056 -0.8138488 ]
 [ 0.01765521 -0.71987283 -0.16529143 -0.3576847 ]]
[[0.03924918 0.8394722  0.13437784 0.00264978]
 [0.90124524 0.6487186  0.6997416  0.9736655 ]
 [0.71825826 0.8216994  0.2848096  0.0893929 ]
 [0.92644405 0.10543382 0.4284302  0.7009642 ]]


In [35]:
for opt in my_ops:
    print(opt.eval())

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0.14549841  0.6867043  -0.01019053  1.0134082 ]
 [ 0.61119354 -0.05097756 -0.28675044 -0.05662883]
 [-1.4103788   0.32996416  0.27841234 -0.15995729]
 [-0.7900137  -0.15310758 -1.3682243   0.66255516]]
[[0.8425057  0.79527426 0.65176225 0.12396359]
 [0.5236771  0.08794117 0.680827   0.6659442 ]
 [0.9409735  0.46752036 0.49559593 0.8920356 ]
 [0.4551338  0.9891864  0.22741306 0.47663593]]


In [36]:
n1 = tf.constant(1)

In [37]:
n2 = tf.constant(2)

In [38]:
n3 = n1 + n2

In [39]:
n3

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [40]:
with tf.Session() as sess:
    print(sess.run(n3))

3


In [41]:
sess = tf.InteractiveSession()

In [42]:
my_tensor = tf.random_uniform((4,4), 0, 1)

In [43]:
my_var = tf.Variable(initial_value=my_tensor)

In [44]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [48]:
init = tf.global_variables_initializer()

In [49]:
sess.run(init)

In [50]:
sess.run(my_var)

array([[0.425835  , 0.03133786, 0.20237279, 0.6654202 ],
       [0.78509986, 0.0266552 , 0.15356338, 0.48394942],
       [0.5405636 , 0.6695181 , 0.6474621 , 0.3984306 ],
       [0.8566855 , 0.8359419 , 0.8317481 , 0.8234488 ]], dtype=float32)